id: P005367
initial_creation_type: ocr
source_metadata:
  id: bdr:W24575
  title: རིག་འཛིན་ཆེན་པོ་དཔལ་ལྡན་བཀྲ་ཤིས་ཀྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས་
  author: ''
  volumes:
    00e1a2a1dc89461f9c1df421f75b9af2:
      image_group_id: I4210
      title: ''
      volume_number: 1
      total_pages: 357
