id: IF546DB57
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:19:08+00:00'
last_modified: '2022-06-08T02:35:02.871058+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W24575
  title: རིག་འཛིན་ཆེན་པོ་དཔལ་ལྡན་བཀྲ་ཤིས་ཀྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8223':
      image_group_id: I4210
      title: ''
      total_pages: 357
      order: 1
      base_file: 8223.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
